export const staticConfig = {
  users: ["User 1", "User 2", "User 3", "User 4", "User 5"],
  dataDirName: "data",
  databaseFileName: "lab-beacon.sqlite",
  timings: {
    checkinIntervalMinutes: 180,
    graceMinutes: 15,
    confirmationWarningMinutes: 120,
    confirmationDangerMinutes: 60,
    pollSeconds: 60,
    gpuIdleWindowMinutes: 10,
    scheduleStartGraceMinutes: 15,
  },
  gpu: {
    idleThreshold: 20,
    busyMinActiveRatio: 0.6,
    busyMinConsecutiveSamples: 3,
    recentSamplesLimit: 28,
    mlProcessMinMemoryMb: 512,
    mlProcessKeywords: [
      "accelerate",
      "cuda",
      "cudnn",
      "cupy",
      "deepspeed",
      "diffusers",
      "ipykernel",
      "jax",
      "jupyter",
      "keras",
      "lightning",
      "onnxruntime",
      "pytorch",
      "tensorflow",
      "torch",
      "transformers",
      "triton",
      "ultralytics",
      "xformers",
    ],
  },
  telegram: {
    botToken: "",
    chatId: "",
    dryRun: true,
  },
  system: {
    nvidiaSmiPath: "nvidia-smi",
  },
} as const;
